import Jacket from '../assets/Jacket.png'
import Suit from '../assets/Suit.png'
import Jeans from '../assets/Jeans.png'
import Gown from '../assets/Gown.png'
import Chic from '../assets/Chic.png'
import Floral from '../assets/Floral.png'
import Tshirt from '../assets/Tshirt.png'
import Jacket2 from '../assets/WomenJacket.png'


export const ProductData = [
    {
        img: Jacket,
        category: "Men's Clothing",
        name: "Casual Jacket",
        price: "$85.50",
    },
    {
        img: Suit,
        category: "Men's Clothing",
        name: "Formal Suit",
        price: "$215.00",
    },
    {
        img: Jeans,
        category: "Men's Clothing",
        name: "Denim Jeans",
        price: "$45.99",
    },
    {
        img: Gown,
        category: "Women's Clothing",
        name: "Evening Gown",
        price: "$120.00",
    },
    {
        img: Chic,
        category: "Women's Clothing",
        name: "Chic Blouse",
        price: "$32.25",
    },
    {
        img: Floral,
        category: "Women's Clothing",
        name: "Floral Skirt",
        price: "$40.00",
    },
    {
        img: Tshirt,
        category: "Men's Clothing",
        name: "Graphic T-Shirt",
        price: "$25.00",
    },
    {
        img: Jacket2,
        category: "Women's Clothing",
        name: "Leather Jacket",
        price: "$150.00",
    },
];



export const AllProductData = [
    {
        id: 1,
        img: Jacket,
        category: "Men's Clothing",
        name: "Casual Jacket",
        price: "$85.50",
    },
    {
        id: 2,
        img: Suit,
        category: "Men's Clothing",
        name: "Formal Suit",
        price: "$215.00",
    },
    {
        id: 3,
        img: Jeans,
        category: "Men's Clothing",
        name: "Denim Jeans",
        price: "$45.99",
    },
    {
        id: 4,
        img: Gown,
        category: "Women's Clothing",
        name: "Evening Gown",
        price: "$120.00",
    },
    {
        id: 5,
        img: Chic,
        category: "Women's Clothing",
        name: "Chic Blouse",
        price: "$32.25",
    },
    {
        id: 6,
        img: Floral,
        category: "Women's Clothing",
        name: "Floral Skirt",
        price: "$40.00",
    },
    {
        id: 7,
        img: Tshirt,
        category: "Men's Clothing",
        name: "Graphic T-Shirt",
        price: "$25.00",
    },
    {
        id: 8,
        img: Jacket2,
        category: "Women's Clothing",
        name: "Leather Jacket",
        price: "$150.00",
    },
    {
        id: 9,
        img: Jacket,
        category: "Men's Clothing",
        name: "Casual Jacket",
        price: "$85.50",
    },
    {
        id: 10,
        img: Tshirt,
        category: "Men's Clothing",
        name: "Slim Fit Shirt",
        price: "$45.00",
    },
    {
        id: 11,
        img: Suit,
        category: "Men's Clothing",
        name: "Blue Jeans",
        price: "$60.00",
    },
    {
        id: 12,
        img: Floral,
        category: "Men's Shoes",
        name: "Sport Sneakers",
        price: "$120.00",
    },
    {
        id: 13,
        img: Jacket2,
        category: "Women's Clothing",
        name: "Summer Dress",
        price: "$70.00",
    },
    {
        id: 14,
        img: Gown,
        category: "Accessories",
        name: "Leather Handbag",
        price: "$110.00",
    },
    {
        id: 15,
        img: Chic,
        category: "Accessories",
        name: "Aviator Sunglasses",
        price: "$25.00",
    },
    {
        id: 16,
        img: Jacket,
        category: "Men's Clothing",
        name: "Comfort Hoodie",
        price: "$55.00",
    },
    {
        id: 17,
        img: Suit,
        category: "Men's Shoes",
        name: "Leather Boots",
        price: "$140.00",
    },
    {
        id: 18,
        img: Suit,
        category: "Women's Clothing",
        name: "Denim Skirt",
        price: "$50.00",
    },
    {
        id: 19,
        img: Tshirt,
        category: "Accessories",
        name: "Classic Watch",
        price: "$150.00",
    },
    {
        id: 20,
        img: Floral,
        category: "Men's Clothing",
        name: "Formal Blazer",
        price: "$180.00",
    },
];

export const ProductInfo = [
    {
      id: 1,
      img: Jacket,
      category: "Men's Clothing",
      name: "Casual Jacket",
      price: "$85.50",
      description: "This casual jacket is perfect for both formal and casual settings. It features a stylish fit with a comfortable, durable fabric.",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Blue", "Gray", "Black"],
      rating: 4.5,
      reviews: 120,
    },
    {
      id: 2,
      img: Suit,
      category: "Men's Clothing",
      name: "Formal Suit",
      price: "$215.00",
      description: "A sleek and elegant formal suit designed for business meetings and special events. Tailored for a sharp look.",
      sizes: ["M", "L", "XL"],
      colors: ["Black", "Navy"],
      rating: 4.8,
      reviews: 95,
    },
    {
      id: 3,
      img: Jeans,
      category: "Men's Clothing",
      name: "Denim Jeans",
      price: "$45.99",
      description: "Comfortable and stylish denim jeans perfect for daily wear. These jeans are made of high-quality cotton for durability.",
      sizes: ["30", "32", "34", "36"],
      colors: ["Blue", "Black"],
      rating: 4.2,
      reviews: 250,
    },
    {
      id: 4,
      img: Gown,
      category: "Women's Clothing",
      name: "Evening Gown",
      price: "$120.00",
      description: "This elegant evening gown is perfect for formal parties and events. Made with premium fabric, it gives a sophisticated look.",
      sizes: ["S", "M", "L"],
      colors: ["Red", "Black", "Gold"],
      rating: 5.0,
      reviews: 45,
    },
    {
      id: 5,
      img: Chic,
      category: "Women's Clothing",
      name: "Chic Blouse",
      price: "$32.25",
      description: "A chic blouse ideal for both work and casual outings. Soft fabric and a flattering cut make it a wardrobe staple.",
      sizes: ["S", "M", "L"],
      colors: ["White", "Pink", "Blue"],
      rating: 4.0,
      reviews: 100,
    },
    {
      id: 6,
      img: Floral,
      category: "Women's Clothing",
      name: "Floral Skirt",
      price: "$40.00",
      description: "A flowy floral skirt that’s perfect for spring and summer outings. Pair it with your favorite top for a casual yet fashionable look.",
      sizes: ["M", "L", "XL"],
      colors: ["Floral Print", "Solid Black"],
      rating: 4.3,
      reviews: 130,
    },
    {
      id: 7,
      img: Tshirt,
      category: "Men's Clothing",
      name: "Graphic T-Shirt",
      price: "$25.00",
      description: "A comfortable graphic t-shirt made of soft cotton. Features cool designs that make a bold statement.",
      sizes: ["M", "L", "XL"],
      colors: ["Black", "White", "Gray"],
      rating: 4.1,
      reviews: 150,
    },
    {
      id: 8,
      img: Jacket2,
      category: "Women's Clothing",
      name: "Leather Jacket",
      price: "$150.00",
      description: "A stylish leather jacket perfect for colder weather. Timeless design that can be dressed up or down.",
      sizes: ["S", "M", "L"],
      colors: ["Black", "Brown"],
      rating: 4.7,
      reviews: 200,
    },
    {
      id: 9,
      img: Jacket,
      category: "Men's Clothing",
      name: "Casual Jacket",
      price: "$85.50",
      description: "A versatile casual jacket designed for everyday wear. Its lightweight material is perfect for the fall season.",
      sizes: ["M", "L", "XL"],
      colors: ["Olive", "Gray", "Navy"],
      rating: 4.5,
      reviews: 180,
    },
    {
      id: 10,
      img: Tshirt,
      category: "Men's Clothing",
      name: "Slim Fit Shirt",
      price: "$45.00",
      description: "A slim-fit shirt that’s both fashionable and comfortable. Great for both casual and semi-formal occasions.",
      sizes: ["S", "M", "L"],
      colors: ["White", "Blue", "Gray"],
      rating: 4.6,
      reviews: 220,
    },
    {
      id: 11,
      img: Suit,
      category: "Men's Clothing",
      name: "Blue Jeans",
      price: "$60.00",
      description: "Classic blue jeans designed for everyday wear. Soft fabric with a relaxed fit for ultimate comfort.",
      sizes: ["30", "32", "34", "36"],
      colors: ["Blue"],
      rating: 4.0,
      reviews: 110,
    },
    {
      id: 12,
      img: Floral,
      category: "Men's Shoes",
      name: "Sport Sneakers",
      price: "$120.00",
      description: "Sport sneakers designed for both comfort and style. Ideal for daily activities or casual outings.",
      sizes: ["8", "9", "10", "11"],
      colors: ["White", "Black"],
      rating: 4.3,
      reviews: 75,
    },
    {
      id: 13,
      img: Jacket2,
      category: "Women's Clothing",
      name: "Summer Dress",
      price: "$70.00",
      description: "A lightweight and comfortable summer dress, perfect for warm weather. The soft fabric ensures all-day comfort.",
      sizes: ["S", "M", "L"],
      colors: ["Pink", "Blue"],
      rating: 4.8,
      reviews: 50,
    },
    {
      id: 14,
      img: Gown,
      category: "Accessories",
      name: "Leather Handbag",
      price: "$110.00",
      description: "A luxurious leather handbag that’s perfect for any occasion. It features spacious compartments for all your essentials.",
      sizes: ["One Size"],
      colors: ["Black", "Brown"],
      rating: 4.6,
      reviews: 180,
    },
    {
      id: 15,
      img: Chic,
      category: "Accessories",
      name: "Aviator Sunglasses",
      price: "$25.00",
      description: "Stylish aviator sunglasses that add a cool factor to any outfit. UV protection for your eyes.",
      sizes: ["One Size"],
      colors: ["Silver", "Gold"],
      rating: 4.4,
      reviews: 90,
    },
    {
      id: 16,
      img: Jacket,
      category: "Men's Clothing",
      name: "Comfort Hoodie",
      price: "$55.00",
      description: "A comfortable hoodie made with soft fabric. Perfect for casual days or for layering during colder months.",
      sizes: ["M", "L", "XL"],
      colors: ["Gray", "Black", "Navy"],
      rating: 4.7,
      reviews: 200,
    },
    {
      id: 17,
      img: Suit,
      category: "Men's Shoes",
      name: "Leather Boots",
      price: "$140.00",
      description: "High-quality leather boots with a stylish design. Perfect for both casual and semi-formal occasions.",
      sizes: ["8", "9", "10", "11"],
      colors: ["Brown", "Black"],
      rating: 4.5,
      reviews: 130,
    },
    {
      id: 18,
      img: Suit,
      category: "Women's Clothing",
      name: "Denim Skirt",
      price: "$50.00",
      description: "A classic denim skirt that can be dressed up or down. A perfect addition to your casual wardrobe.",
      sizes: ["S", "M", "L"],
      colors: ["Blue", "Black"],
      rating: 4.1,
      reviews: 160,
    },
    {
      id: 19,
      img: Tshirt,
      category: "Accessories",
      name: "Classic Watch",
      price: "$150.00",
      description: "A timeless classic watch with a sleek design. Perfect for both casual and formal events.",
      sizes: ["One Size"],
      colors: ["Silver", "Gold"],
      rating: 4.9,
      reviews: 220,
    },
    {
      id: 20,
      img: Floral,
      category: "Men's Clothing",
      name: "Formal Blazer",
      price: "$180.00",
      description: "A formal blazer that provides a sharp and sophisticated look for any formal occasion.",
      sizes: ["M", "L", "XL"],
      colors: ["Black", "Navy"],
      rating: 4.7,
      reviews: 180,
    },
  ];
  